language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini

install: composer install

script:
  - composer validate
  - ./vendor/bin/phpunit --testdox
