language: php

matrix:
  include:
    - php: 7.1
      env: COMPOSER_FLAGS=--prefer-lowest WITH_CS=true
    - php: 7.1
    - php: 7.2
      env: COMPOSER_FLAGS=--prefer-lowest
    - php: 7.2
    - php: 7.3
      env: COMPOSER_FLAGS=--prefer-lowest
    - php: 7.3

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini

install:
  - composer update $COMPOSER_FLAGS

script:
  - composer validate
  - if [[ "$WITH_CS" == "true" ]]; then ./vendor/bin/php-cs-fixer fix --diff --dry-run --verbose; fi
  - ./vendor/bin/phpunit --testdox
