language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6

branches:
  only:
  - master

install: composer install

script:
  - composer validate
  - phpunit --testdox
#script: phpunit --coverage-text
